version: "3"
services:
    rabbitmq:
        image: rabbitmq:latest
        ports:
            - 6379:6379
    node1:
        image: python:celery-test
        volumes:
            - ./src:/app/src
        command: bash -c "python /app/worker1/task1.py"
    node2:
        image: python:celery-test
        volumes:
            - ./src:/app/src
        command: bash -c "export PYTHONPATH=/app/src/worker2; celery worker -A task2 -Q Queue2 --loglevel=info"
    node3:
        image: python:celery-test
        volumes:
            - ./src:/app/src

